### ISSUE TITLE
Keyboard Key Colors override

### ISSUE THREAD

**Issue by CapitalIdea** [SamuelQuinones/svelte-wordle#1]
It seems when a letter is used twice in a word and the first instance of that letter is yellow and the second is grey the keyboard key is represented as grey. Additionally, when you already have a key colored yellow and the above issue is created it resets back to grey. Images 1 and 2 display theses bugs respectively. Note that this does no occur when the key turns green. 

![image](https://github.com/SamuelQuinones/svelte-wordle/assets/16947900/6e002fbb-438b-4830-b860-c13a5805006b)

![image](https://github.com/SamuelQuinones/svelte-wordle/assets/16947900/2e29d686-e5f9-492c-a102-4f05c7adf6da)

**Comment by SamuelQuinones** [comment]
Issue appears to be a logic bug in the keyboard store file. It looks like the value gets overwritten with whatever the most recent value is

**Comment by SamuelQuinones** [comment]
Fixed by #2
